Bugfix issue144 (#146)
* Preliminary fix for issue #144

* Fixing option passing

* Opening the config file in w+ mode

* [ERROR] --gtid-mode=ON or UPGRADE_STEP_1 or UPGRADE_STEP_2 requires --log-bin and --log-slave-updates

* Preliminary fix for issue #144

* Added slave_count option to config generator

* Changd start_mysql_func() to accept start tool as well

* First test run

* TypeError: prepare_start_slave_options() missing 2 required positional arguments: 'basedir' and 'slave_number'

* TypeError: prepare_start_slave_options() missing 1 required positional argument: 'slave_number'

* [ERROR] The socket file path is too long (> 107): /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/node0/slave_socket.sock

* Now trying to fix slave start up problem

* Added few tests and also pt-table-checksum run

* Added assert statement

* Trying to make started server to be slave

* Added unit test test_run_change_master()

* Added returns to method

* Trying to fix sql error

* Trying to fix sql error again

* Trying to escape characters

* Escaping some characters here also

* Checking again for failed thing

* Passing master port for slave's change master statement

* Fixed port checking call

* Found the value of port

* Passing port number to change master statement

* Trying to pass proper create statement

* Passed true values for master server

* Fix the string

* Successfully made the started node as slave

* Added run for pt-table-checksum tool on master

* Trying to run pt-table-checksum on master server

* TypeError: 'int' object is not iterable

* Fixing some dependent tasks

* Passing start slave command to slave server

* Trying to fix this weird situation on returning True from method

* Check if prepare methods also returning something

* returning True from functions

* Changed the structure of run_change_master()

* Raising RuntimeError here

* Added new check_slave_output() static method

* Fixing open issue for stop_node{} file

* Added sleep(10)

* Fixing small things

* Giving some sleep(10)

* Added new debug message

* Added few mor fixes here

* Added drop_blank_mysql_users() static method

* Trying to fix failed test

* Again trying to fix failed test sql syntax error

* Next attempt

* next attempt n2

* seems to be final attempt

* Finalized dropping blank users

* Added final docstrings and other checks

* Changed binlog_format to row

* Added get_gtid_address() static method

* Running gtid_purged

* RuntimeError: Failed to run SQL command -> ERROR 1193 (HY000) at line 1: Unknown system variable 'gitd_purged'

* Increased the sleep time

* Added pytest for check_slave_status()

* Could find the fail reason. it was due to not using lstrip()

* Changed assert to check against None

* Added new tests and create_dsns_table()

* Creating table

* Added pytest test_populate_dsns_table()

* Fix for failed mysql client command

* for the right syntax to use near 's=/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-l' at line 1

* Another sql syntax error

* Adding some fix for sql syntax

* Again trying to fix sql syntax issue

* Added --recursion-method

* Added pytest test_run_pt_table_checksum()

* Using localhost instead of ip

* removed p=

* Passing slave port

* changed to 127.0.0.1

* Finalizing the #144 implementation